AllCops:
  TargetRubyVersion: 2.3
  DisplayCopNames: true
  DisplayStyleGuide: true

Layout/AlignHash:
  EnforcedHashRocketStyle: table
  EnforcedColonStyle: table

Layout/IndentFirstArgument:
  EnforcedStyle: consistent

Layout/IndentFirstArrayElement:
  EnforcedStyle: consistent

Layout/IndentFirstHashElement:
  EnforcedStyle: consistent

Metrics/BlockLength:
  Exclude:
    - '*.gemspec'
  ExcludedMethods:
    - 'describe'
    - 'context'

Metrics/ClassLength:
  Enabled: false

Metrics/LineLength:
  Max: 90

Style/BracesAroundHashParameters:
  EnforcedStyle: context_dependent
