sudo: false
language: ruby
cache: bundler
script: bundle exec rspec
rvm:
  - 2.7
  - 2.6
  - 2.5
  - 2.4
  - 2.3
branches:
  only: master
notifications:
  email: false
env:
  global:
    - CC_TEST_REPORTER_ID=ca61b641c417ff48e8cff3c0d10e5503539bf81348b0df8daca6c74e2401d4e4
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
